### PR TITLE
Adding Styles to Author Comments

### PR DESCRIPTION
**Pull request by BFTrick**
This pull request adds styles to the author comments as discussed in #28.

I couldn't figure out a way to get CodeKit's LESS compiler to leave the whitespace alone so the first commit is just recompiling style.css. The second commit actually has the diff you want.

I thought about just submitting the second pull commit to you but if other users use CodeKit then we might as well pull these code-style changes in right?

### CODE REVIEW

**Comment by BFTrick** [comment]
It looks like this:

author-comment-styles

**Comment by jameskoster** [comment]
Thanks @BFTrick ! That compiling issue is odd, I'm using codekit too so dunno why it would be different o_O

**Comment by jameskoster** [comment]
You forgot to account for the theme options ;-P Not to worry, I'll handle that at some point.

**Comment by BFTrick** [comment]
Ack sorry. For some reason I thought that was all taken care of with your LESS variables and forgot about changing the theme customizer files. :(

**Pull request merged**
